### ISSUE TITLE
Updating from 4.3.0 to 4.5.0 causes crashes when rotating

### ISSUE THREAD

**Issue by jt-gilkeson** [MobileAppTracking/sdk-release#21]
Updated from 4.3.0 to 4.5.0 and we see the following crash when rotating the phone.  (If I simply change back to 4.3.0 with no code changes the crash doesn't happen).

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{MyActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.support.v4.app.FragmentHostCallback.getContext()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.support.v4.app.FragmentHostCallback.getContext()' on a null object reference
       at android.support.v4.app.FragmentState.instantiate(Fragment.java:100)
       at android.support.v4.app.FragmentManagerImpl.restoreAllState(FragmentManager.java:2053)
       at android.support.v4.app.Fragment.restoreChildFragmentState(Fragment.java:1282)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
       at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2144)
       at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:190)
       at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:351)
       at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
       at com.gogobot.utilities.app.GogoActivity.onCreate(GogoActivity.java:41)
       at com.gogobot.gogodroid.GogobotMenuActivity.onCreate(GogobotMenuActivity.java:357)
       at android.app.Activity.performCreate(Activity.java:6251)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by john-gu** [comment]
Hi @jt-gilkeson, 4.4.0 updated our v4-support library versions to v24. Could this be affecting your v4 classes?

**Comment by jt-gilkeson** [comment]
Not sure, we are using Support Lib 23.4.0.  

24.x causes some breaking changes in themes, so we haven't had time to update to it yet.

**Comment by jt-gilkeson** [comment]
I just set transitive to true, which seems to prevent the crash:

```
    compile('com.tune:tune-marketing-console-sdk:4.5.0') {
        transitive = true
    }
```

**Comment by jt-gilkeson** [comment]
It looks like this may have solved the issue for me:

```
   compile('com.tune:tune-marketing-console-sdk:4.5.0') {
        exclude module: 'support-v4'
    }

```

**Comment by john-gu** [comment]
Great, glad to hear you found a fix! I'll close this out for now, please let us know if you have issues when you do update to v24.
